In [21]:
import astropy.units as units
import astropy.constants as constants
import matplotlib.pyplot as plt
import sympy as sym
import numpy as np 
import pandas as pd
import plotly.express as px
import plotly.figure_factory as ff
import plotly.graph_objects as go
import requests
import re
import subprocess
import urllib.request
from sympy.abc import *
from bs4 import BeautifulSoup
import csv
cwd = subprocess.os.getcwd()

In [22]:
def half_life_to_lambda(half_life):
    '''
    This function takes the e-folding times of the entire decay chain.
    Returns the half-life of the nuclide
    '''
    return half_life / np.log(2)

nuclide_df = pd.read_csv(cwd + '\\NuclideData.csv').iloc[:,1:]
half_lives = nuclide_df['Half life (years)'].to_numpy() 
nuclide_df["e Folding Time (seconds)"] = half_life_to_lambda(half_lives * units.year.to(units.s))
nuclide_df

Beta-decay energy (keV)  Half life (years) Isotope  Beta-decay fraction  \
0                          *       4.182828e-10    63Se                  0.0   
1                 21661.2131       2.725176e-30      5H                  0.0   
2                     -217.0       3.580754e-07   272Bh                  0.0   
3                 -13088.708       7.115560e-07    21Na                  0.0   
4                          *       9.506426e-10    82Mo                  0.0   
...                      ...                ...     ...                  ...   
3187               9925.3249       2.851928e-08   106Nb                  1.0   
3188                 22940.0       3.168809e-11     59K                  0.0   
3189               1047.6178       2.564834e-05   146Ce                  1.0   
3190              -4581.6095       8.156514e-04    73Se                  0.0   
3191                       *       4.008543e-09      9C                  0.0   

      Average beta decay energy  e Folding Time (seconds)  
0                          5.69              1.904357e-02  
1                          5.69              1.240718e-22  
2                          5.69              1.630245e+01  
3                          5.69              3.239572e+01  
4                          5.69              4.328085e-02  
...                         ...                       ...  
3187                       5.69              1.298426e+00  
3188                       5.69              1.442695e-03  
3189                       5.69              1.167717e+03  
3190                     284.00              3.713497e+04  
3191                       5.69              1.825009e-01  

[3192 rows x 6 columns]

In [23]:
element_symbols = ['H', 'He', 'Li', 'Be', 'B', 'C', 'N', 'O', 
'F', 'Ne', 'Na', 'Mg', 'Al', 'Si', 'P', 'S', 'Cl', 'Ar', 'K', 
'Ca', 'Sc', 'Ti', 'V', 'Cr', 'Mn', 'Fe', 'Co', 'Ni', 'Cu', 
'Zn', 'Ga', 'Ge', 'As', 'Se', 'Br', 'Kr', 'Rb', 'Sr', 'Y', 
'Zr', 'Nb', 'Mo', 'Tc', 'Ru', 'Rh', 'Pd', 'Ag', 'Cd', 'In', 
'Sn', 'Sb', 'Te', 'I', 'Xe', 'Cs', 'Ba', 'La', 'Ce', 'Pr', 
'Nd', 'Pm', 'Sm', 'Eu', 'Gd', 'Tb', 'Dy', 'Ho', 'Er', 'Tm',
 'Yb', 'Lu', 'Hf', 'Ta', 'W', 'Re', 'Os', 'Ir', 'Pt', 'Au', 
 'Hg', 'Tl', 'Pb', 'Bi', 'Po', 'At', 'Rn', 'Fr', 'Ra', 'Ac', 
 'Th', 'Pa', 'U', 'Np', 'Pu', 'Am', 'Cm', 'Bk', 'Cf', 'Es', 
 'Fm', 'Md', 'No', 'Lr', 'Rf', 'Db', 'Sg', 'Bh', 'Hs', 'Mt',
  'Ds', 'Rg', 'Cn', 'Nh', 'Fl', 'Mc', 'Lv', 'Ts', 'Og', 'N/A']
len(element_symbols)
#to find the daughter nuclide we only need to increment by 1 in the element symbols.
element_symbols[element_symbols.index('Ni')+1]
#remove numbers from string
s = element_symbols
nuclide_df['Daugher Nucleus'] = [re.sub('\D+', '', n) + s[s.index(re.sub('\d+', '', n))+1] 
if re.sub('\d+', '', n) in s else 'N/A' for n in nuclide_df['Isotope'] ]

In [24]:
def get_isotope_info(isotope, info = None, isotope_column = None,
    dataset = {}, isotope_list = None, lists_to_search = []):                  
  '''
  isotope_list and list_to_search are optional arguments.
  If list_to_search is not provided, then info must be provided.
  If isotope_list is not provided, then dataset and isotope_column
  must be provided.
  '''
  if isotope_list is None:
    isotope_list = list(dataset[isotope_column])
  row = isotope_list.index(isotope)
  if len(lists_to_search) == 0:
    try:
      lists_to_search = list(dataset[info])
    except:
      print("info to search for not entered")
      return
  try: #only works if there are multiple specified lists to search 
    return [target_list[row] for target_list in lists_to_search]
  except:
    return lists_to_search[row]


In [25]:
isotope_list = list(nuclide_df['Isotope'])
lambda_list = list(nuclide_df['e Folding Time (seconds)'])
decay_energy_list = list(nuclide_df['Average beta decay energy'])
daughter_list = list(nuclide_df['Daugher Nucleus'])

In [26]:
def make_decay_chain(isotope, isotope_list, lambda_list, decay_energy_list, daughter_list):
    '''
    This function takes the isotope, e-folding times, and daughter nuclides
    and returns the decay chain.
    '''
    decay_chain = {}
    decay_chain[isotope] = get_isotope_info(isotope, isotope_list = isotope_list, 
        lists_to_search = (lambda_list, decay_energy_list, daughter_list))
    while True:
        isotope = decay_chain[isotope][2]
        try:
            decay_chain[isotope] = get_isotope_info(isotope, isotope_list = isotope_list,
                lists_to_search = (lambda_list, decay_energy_list, daughter_list))
            if(isotope == decay_chain[isotope][2]):
                return decay_chain
        except:
            return pd.DataFrame(decay_chain, index= ("e-Folding Time (seconds)", 
                                "Average beta-decay energy", "Daughter")).transpose()


In [27]:
#Quickly calculating the decay rate of the i-th generation nuclide
def formulate_decay_rate(e_folding_times):
    '''
    The e-folding times must be in a numpy array.
    Returns a formula for the decay rate of each generation. 
    '''
    exponent_array = -1 / e_folding_times
    decay_rates = len(exponent_array)  * [sym.N(0)]
    decay_rates[0] = sym.exp(t * exponent_array[0]) * exponent_array[0]
    for index, L in enumerate(exponent_array[1:]):
        decay_rates[index+1] = decay_rates[index] * (1 + sym.exp(t * L) * L) 
    return decay_rates

def eval_decay_rates(decay_rates, time_array):
    '''
    This function takes the formula for the decay rate of each generation
    and substitutes each value in the time array for t.
    Each decay_rate must be a sympy expression. 
    https://docs.sympy.org/ 
    Rewrite so that the outer loop is over the time array and the inner loop
    is over the generations. This can be done by using (suggested by copilot: 
    the np.meshgrid function) or a 2d array (my first thought)
    '''
    try: #will only evaluate if decay_rates is an array of sympy expressions
        evaluated_decay_rates = [np.array([formula.subs(t, time) for formula in decay_rates])
                                    for time in time_array]
    except:
        evaluated_decay_rates = [decay_rates.subs(t, time) for time in time_array]
    return evaluated_decay_rates


#Calculating the power density of a decay chain
def calc_power_density(decay_rates, decay_energies, initial_mass):
    '''
    Rewrite such that is sums the entire chain and NOT across time
    decay_rates must be a numpy array in moles/second
    decay_energies must be a numpy array in keV/decay
    This function takes the decay rates and energies of the decay chain.
    Returns the power density in watts/g
    '''
    power_density =  [sum(decay_rate_t * decay_energies) for decay_rate_t in decay_rates]
    '''
    At every different value for time, 
    store the sum of the product of each generation's decay rate and decay energy.
    '''
    power_density = np.array(power_density)
    #convert to W/g
    power_density *=  units.keV.to(units.J) * float(constants.N_A * units.mol) / initial_mass
    return np.abs(power_density.astype(float))


In [28]:
chain = make_decay_chain('32Si', isotope_list, lambda_list, decay_energy_list, daughter_list)
chain

e-Folding Time (seconds) Average beta-decay energy Daughter
32Si              7.14789e+09                      68.8      32P
32P               1.77861e+06                     694.9      32S

In [29]:
decay_rates = formulate_decay_rate(chain['e-Folding Time (seconds)'])
#currently, eval_decay_rates evalautes in < 1 second for 100 time points and 6 generations
time_array = np.logspace(1, 9.5, 10**2)
n_decay_rates = eval_decay_rates(decay_rates, time_array)
n_decay_rates

[array([-1.39901329266888e-10, -1.39901250609852e-10], dtype=object),
 array([-1.39901329224105e-10, -1.39901250567165e-10], dtype=object),
 array([-1.39901329171969e-10, -1.39901250515147e-10], dtype=object),
 array([-1.39901329108436e-10, -1.39901250451758e-10], dtype=object),
 array([-1.39901329031016e-10, -1.39901250374512e-10], dtype=object),
 array([-1.39901328936672e-10, -1.39901250280382e-10], dtype=object),
 array([-1.39901328821705e-10, -1.39901250165675e-10], dtype=object),
 array([-1.39901328681607e-10, -1.39901250025894e-10], dtype=object),
 array([-1.39901328510885e-10, -1.39901249855557e-10], dtype=object),
 array([-1.39901328302845e-10, -1.39901249647987e-10], dtype=object),
 array([-1.39901328049328e-10, -1.39901249395043e-10], dtype=object),
 array([-1.39901327740394e-10, -1.39901249086808e-10], dtype=object),
 array([-1.39901327363930e-10, -1.39901248711194e-10], dtype=object),
 array([-1.39901326905173e-10, -1.39901248253474e-10], dtype=object),
 array([-1.399013263

In [30]:
t_power_densities = calc_power_density(decay_rates = n_decay_rates, decay_energies = np.array(chain['Average beta-decay energy']),
        initial_mass = float(re.sub('\D+', '', chain.index[0])))
px.scatter(y=t_power_densities, x= time_array, log_x=True, log_y=True,
        labels={'x': 'Time (seconds)', 'y': 'Power Density (W/g)'}, title = 'Power Density of ' + chain.index[0] + ' Decay Chain')
#THIS IS MUCH HIGHER THAN WHAT I HAVE IN THE DECADE HALF LIVES POWER DENSITIES ON GITHUB!!!
#Double check decay formulas!!!!

In [31]:
time_array

array([1.00000000e+01, 1.21859274e+01, 1.48496826e+01, 1.80957154e+01,
       2.20513074e+01, 2.68715631e+01, 3.27454916e+01, 3.99034183e+01,
       4.86260158e+01, 5.92553098e+01, 7.22080902e+01, 8.79922544e+01,
       1.07226722e+02, 1.30665705e+02, 1.59228279e+02, 1.94034425e+02,
       2.36448941e+02, 2.88134963e+02, 3.51119173e+02, 4.27871275e+02,
       5.21400829e+02, 6.35375264e+02, 7.74263683e+02, 9.43512101e+02,
       1.14975700e+03, 1.40108553e+03, 1.70735265e+03, 2.08056754e+03,
       2.53536449e+03, 3.08957676e+03, 3.76493581e+03, 4.58792343e+03,
       5.59081018e+03, 6.81292069e+03, 8.30217568e+03, 1.01169710e+04,
       1.23284674e+04, 1.50233808e+04, 1.83073828e+04, 2.23092437e+04,
       2.71858824e+04, 3.31285189e+04, 4.03701726e+04, 4.91947992e+04,
       5.99484250e+04, 7.30527154e+04, 8.90215085e+04, 1.08480964e+05,
       1.32194115e+05, 1.61090788e+05, 1.96304065e+05, 2.39214708e+05,
       2.91505306e+05, 3.55226249e+05, 4.32876128e+05, 5.27499706e+05,
      

In [32]:
all_decay_chains = [make_decay_chain(isotope, isotope_list, lambda_list, decay_energy_list, daughter_list) 
                    for isotope in isotope_list]
time_array = np.logspace(1, 9.5, 10)
def calculate_all_power_densities(all_decay_chains, time_array, mean = True):
    '''
    This function takes the isotope, e-folding times, and daughter nuclides
    and returns power density as a function of time for each decay chain.
    The optional boolean argument mean determines whether the whole time series is returned
    or only its mean. 
    '''
    if mean:
        all_power_densities = [np.mean(calc_power_density(
                                    decay_rates = eval_decay_rates(
                                                    formulate_decay_rate(chain['e-Folding Time (seconds)']), 
                                                    time_array), 
                                    decay_energies = np.array(chain['Average beta-decay energy']),
                                    initial_mass = float(re.sub('\D+', '', chain.index[0]))
                                )) for chain in all_decay_chains]
    else:
        all_power_densities = [calc_power_density(
                                    decay_rates = eval_decay_rates(
                                                    formulate_decay_rate(chain['e-Folding Time (seconds)']), 
                                                    time_array), 
                                    decay_energies = np.array(chain['Average beta-decay energy']),
                                    initial_mass = float(re.sub('\D+', '', chain.index[0]))
                                ) for chain in all_decay_chains]
    return all_power_densities

mean_power_densities = calculate_all_power_densities(all_decay_chains[:2], time_array, mean = True)


In [199]:
3.7 * len(all_decay_chains) * units.second.to(units.h) / 2
#it will take 2 hours to run my script in jupyter. I'l convert it to a python script and run it in pypy to see if it's faster.


1.6403333333333336

In [200]:
#Import the file exported on colab
relative_path = '\MeanPowerDensitiesofDecayChains\SortedPowerDensities1yto100yMean.csv'
rho_p_1_100 = pd.read_csv(cwd + relative_path).rename(
        columns={'Unnamed: 0': 'Unsorted Index', 
        'Mean Power Density Over 100 years (watts per gram)':'Power Density (W/g)'})
rho_p_1_100 #power density by chain with 100 points in the time series from 1y to 100y.

Unsorted Index Parent Isotope  Power Density (W/g)
0                422          228Th             8.911231
1               1913          254Es             8.316062
2               1881          228Ra             6.341824
3                323           57Co             6.085650
4               2043          252Es             5.031617
...              ...            ...                  ...
3187            1153          155Sm             0.000000
3188            1154           51Ar             0.000000
3189            1155          111Sn             0.000000
3190            1156            14O             0.000000
3191            3191             9C             0.000000

[3192 rows x 3 columns]

In [218]:
#Evaluate the product of power density of the chain and half life of the parent
def eval_battery(half_life, power_density):
    evaluation = 0
    try:
        half_life = min(half_life, 100)
        half_life = half_life / 20
        coeff = min(half_life, power_density) ** 2
        if coeff > 0:
            evaluation = max(0, (coeff * half_life * power_density))
    except: 
        return 0
    return evaluation

parent_half_lives = [all_decay_chains[unsorted_index]['e-Folding Time (seconds)'][0] 
                        / units.year.to(units.second) for row, unsorted_index 
                in enumerate(rho_p_1_100['Unsorted Index'])]
evaluations = [eval_battery(half_life, rho_p_1_100['Power Density (W/g)'][row])
                for row, half_life in enumerate(parent_half_lives)]    
rho_p_1_100['Evaluation'] = np.array(evaluations).astype(float) / max(evaluations)
rho_p_1_100['Half Life (years)'] = np.array(parent_half_lives).astype(float)
#sort dataframe by evaluations
rho_p_1_100 = rho_p_1_100.sort_values(by = 'Evaluation', ascending = False)
rho_p_1_100

Unsorted Index Parent Isotope  Power Density (W/g)  Evaluation  \
24              1262           232U             0.646514    1.000000   
26               281          148Gd             0.536984    0.950164   
27              2994          238Pu             0.516339    0.724595   
35                27          209Po             0.340226    0.695325   
36               397           32Si             0.294311    0.574895   
...              ...            ...                  ...         ...   
3039            1196          125Ru             0.000000    0.000000   
3040            1197          140Dy             0.000000    0.000000   
3041            1198          268Ds             0.000000    0.000000   
3042            1199          156Ho             0.000000    0.000000   
3191            3191             9C             0.000000    0.000000   

      Half Life (years)  
24         9.940169e+01  
26         1.028642e+02  
27         1.265244e+02  
35         1.788942e+02  
36         2.265031e+02  
...                 ...  
3039       5.485950e-10  
3040       3.200137e-08  
3041       4.571625e-12  
3042       1.536066e-04  
3191       5.783105e-09  

[3192 rows x 5 columns]

In [221]:
px.scatter(rho_p_1_100 , x = 'Half Life (years)', 
            y = 'Power Density (W/g)', log_x = True,
            hover_name = 'Parent Isotope',
            color = 'Evaluation', color_continuous_scale = 'algae')
            

In [34]:
all_decay_chains[0].index[0]

'63Se'

In [46]:
def clean_time_series(time_series):
    '''
    This function takes the time series of power densities and returns a list
    of lists of the time series converted into floats.
    '''
    split_time_series = time_series.replace('[', ' ').replace(']', ' ').replace('\n', ' ').split(' ') 
    return np.array([float(power_density) for power_density in split_time_series if len(power_density)>0])

time_series_file_path = cwd + '\MeanPowerDensitiesofDecayChains\power_density_time_series.csv'
#read the file to a numpy array
with open(time_series_file_path, newline='\n') as f:
    reader = csv.reader(f)
    time_series_unclean = list(reader)[0]
power_densities_dict = {}
power_densities_dict['Time (seconds)'] = np.logspace(0, 9.5, 10**3)
for row, chain in enumerate(all_decay_chains):
    power_densities_dict[chain.index[0]] = clean_time_series(time_series_unclean[row])
power_densities_df = pd.DataFrame.from_dict(power_densities_dict).set_index(
                        'Time (seconds)')
power_densities_df

63Se   5H       272Bh        21Na      82Mo  \
Time (seconds)                                                        
1.000000e+00    7.164433e-15  0.0  435636.522  1550902.27  0.014293   
1.022138e+00    2.240368e-15  0.0  439796.858  1551523.68  0.008570   
1.044766e+00    6.827792e-16  0.0  443847.065  1551949.04  0.005081   
1.067895e+00    2.026829e-16  0.0  447782.550  1552191.70  0.002977   
1.091536e+00    5.857026e-17  0.0  451599.079  1552264.34  0.001724   
...                      ...  ...         ...         ...       ...   
2.897090e+09    0.000000e+00  0.0       0.000        0.00  0.000000   
2.961225e+09    0.000000e+00  0.0       0.000        0.00  0.000000   
3.026781e+09    0.000000e+00  0.0       0.000        0.00  0.000000   
3.093788e+09    0.000000e+00  0.0       0.000        0.00  0.000000   
3.162278e+09    0.000000e+00  0.0       0.000        0.00  0.000000   

                     127Cd          258Md       209Ac       141Ba       162Sm  \
Time (seconds)                                                                  
1.000000e+00    41450532.8   1.658466e+00  24304.3496  141396.698  673019.510   
1.022138e+00    40422679.9   1.660066e+00  20644.0007  141394.719  669205.401   
1.044766e+00    39392628.8   1.661693e+00  17471.6169  141392.696  665329.193   
1.067895e+00    38361178.8   1.663347e+00  14732.1856  141390.628  661390.376   
1.091536e+00    37329151.5   1.665030e+00  12375.4438  141388.514  657388.459   
...                    ...            ...         ...         ...         ...   
2.897090e+09           0.0  4.387020e-196      0.0000       0.000       0.000   
2.961225e+09           0.0  2.045293e-200      0.0000       0.000       0.000   
3.026781e+09           0.0  7.646328e-205      0.0000       0.000       0.000   
3.093788e+09           0.0  2.281072e-209      0.0000       0.000       0.000   
3.162278e+09           0.0  5.403110e-214      0.0000       0.000       0.000   

                ...       204Ir       267Rf       221Ac        209Hg   8C  \
Time (seconds)  ...                                                         
1.000000e+00    ...  1884568.96  1084.06282  322.935864  228070688.0  0.0   
1.022138e+00    ...  1870290.94  1084.07979  240.413519  227516629.0  0.0   
1.044766e+00    ...  1855808.44  1084.09594  177.813345  226951645.0  0.0   
1.067895e+00    ...  1841121.00  1084.11150  130.638104  226375559.0  0.0   
1.091536e+00    ...  1826228.34  1084.12667   95.325971  225788192.0  0.0   
...             ...         ...         ...         ...          ...  ...   
2.897090e+09    ...        0.00     0.00000    0.000000          0.0  0.0   
2.961225e+09    ...        0.00     0.00000    0.000000          0.0  0.0   
3.026781e+09    ...        0.00     0.00000    0.000000          0.0  0.0   
3.093788e+09    ...        0.00     0.00000    0.000000          0.0  0.0   
3.162278e+09    ...        0.00     0.00000    0.000000          0.0  0.0   

                     106Nb            59K       146Ce        73Se           9C  
Time (seconds)                                                                  
1.000000e+00    51446960.9  6.136452e-291  6433.34660  10506.5861  1394383.480  
1.022138e+00    50584906.3  1.330511e-297  6433.22465  10506.5827  1235096.610  
1.044766e+00    49718680.4  2.053828e-304  6433.10000  10506.5793  1091071.910  
1.067895e+00    48848591.8  2.240221e-311  6432.97260  10506.5758   961199.958  
1.091536e+00    47974961.3  1.713415e-318  6432.84238  10506.5722   844414.437  
...                    ...            ...         ...         ...          ...  
2.897090e+09           0.0   0.000000e+00     0.00000      0.0000        0.000  
2.961225e+09           0.0   0.000000e+00     0.00000      0.0000        0.000  
3.026781e+09           0.0   0.000000e+00     0.00000      0.0000        0.000  
3.093788e+09           0.0   0.000000e+00     0.00000      0.0000        0.000  
3.162278e+09           0.0   0.000000e+00     0.00000      0.0000       

In [48]:
#plot each column as a line with the index as the x axis
for column in power_densities_df.columns:
    px.line(power_densities_df[column])
